export const lesson = {
  id: 'L04',
  title: 'Types of Attackers & Motivations',
  slug: 'types-of-attackers',
  type: 'THEORY',
  duration: 25,
  xpReward: 15,
  difficulty: 'beginner',
  module: { title: 'Introduction to Cybersecurity', slug: 'intro-cybersecurity' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['Script Kiddie', 'Hacktivist', 'APT', 'Nation-State', 'Insider Threat', 'Cybercriminal', 'Black Hat', 'White Hat'],
  content: [
    { type: 'heading', content: 'Types of Attackers & Motivations' },
    { type: 'paragraph', content: "Not all attackers are the same. Understanding WHO is attacking and WHY helps you predict their methods, targets, and persistence. A script kiddie scanning for easy targets requires different defenses than a nation-state conducting espionage." },
    { type: 'heading', level: 2, content: 'Attacker Categories' },
    { type: 'heading', level: 3, content: '1. Script Kiddies' },
    { type: 'list', items: ["Skill: Low — uses pre-built tools without understanding them", "Motivation: Fun, bragging rights, curiosity", "Methods: Download exploit tools, run automated scanners, deface websites", "Danger: Low individually, but HIGH in volume (millions of automated scans daily)", "Defense: Basic security hygiene stops 95% of script kiddie attacks"] },
    { type: 'heading', level: 3, content: '2. Cybercriminals' },
    { type: 'list', items: ["Skill: Low to High (organized crime hires skilled hackers)", "Motivation: MONEY — ransomware, data theft, fraud, cryptomining", "Methods: Phishing, ransomware, credential stuffing, business email compromise", "Danger: HIGH — responsible for the majority of breaches", "Example: REvil ransomware gang made $100M+ before being disrupted"] },
    { type: 'heading', level: 3, content: '3. Hacktivists' },
    { type: 'list', items: ["Skill: Moderate", "Motivation: Political or social causes — make a statement", "Methods: DDoS attacks, website defacement, data leaks (doxing)", "Danger: Moderate — usually target specific organizations they oppose", "Example: Anonymous group DDoS attacks against governments and corporations"] },
    { type: 'heading', level: 3, content: '4. Nation-State Actors (APTs)' },
    { type: 'list', items: ["Skill: VERY HIGH — government-funded teams with unlimited resources", "Motivation: Espionage, sabotage, military advantage, economic theft", "Methods: Zero-days, custom malware, supply chain attacks, long-term persistence", "Danger: CRITICAL — can compromise any target given enough time", "Examples: APT29 (Russia/SolarWinds), APT41 (China), Lazarus Group (North Korea)"] },
    { type: 'heading', level: 3, content: '5. Insider Threats' },
    { type: 'list', items: ["Skill: Varies — but they already HAVE access (no hacking needed)", "Motivation: Disgruntlement, financial gain, coercion, accidental mistakes", "Methods: Data theft, sabotage, selling credentials, accidental data exposure", "Danger: HIGH — they bypass all perimeter defenses (already inside)", "Statistic: 60% of breaches involve insiders (intentional or accidental)"] },
    { type: 'heading', level: 2, content: 'Hat Classification' },
    { type: 'list', items: ["White Hat — Ethical hackers who find vulnerabilities WITH permission (pentesters)", "Black Hat — Malicious hackers who break into systems WITHOUT permission (criminals)", "Grey Hat — Find vulnerabilities without permission but report them (legally risky)"] },
    { type: 'heading', level: 2, content: 'Motivation Summary Table' },
    { type: 'list', items: ["Money: Cybercriminals, some insiders", "Ideology: Hacktivists", "Espionage: Nation-states", "Fun/Challenge: Script kiddies, some grey hats", "Revenge: Disgruntled insiders", "Warfare: Nation-states, military operations"] },
    { type: 'callout', variant: 'security', content: "Know your adversary: If you are a bank, your primary threat is cybercriminals (money). If you are a defense contractor, it is nation-states (espionage). If you are a social media company, it is hacktivists (ideology). Tailor your defenses to your most likely attackers." },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: ["Different attackers have different skills, motivations, and methods", "Cybercriminals (money) are the most common threat to most organizations", "Nation-states (espionage) are the most dangerous but target fewer organizations", "Insider threats bypass perimeter security — require different detection strategies", "Next: Security frameworks that guide how organizations defend against all of these"] },
  ],
  navigation: {
    prev: { title: 'Threats, Vulnerabilities & Risks', slug: 'threats-vulnerabilities-risks' },
    next: { title: 'Security Controls & Frameworks', slug: 'security-controls-frameworks' },
  },
};
