export const lesson = {
  id: 'L05',
  title: 'Security Controls & Frameworks',
  slug: 'security-controls-frameworks',
  type: 'THEORY',
  duration: 30,
  xpReward: 15,
  difficulty: 'beginner',
  module: { title: 'Introduction to Cybersecurity', slug: 'intro-cybersecurity' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['NIST', 'ISO 27001', 'CIS Controls', 'Framework', 'Control', 'Preventive', 'Detective', 'Corrective'],
  content: [
    { type: 'heading', content: 'Security Controls & Frameworks' },
    { type: 'paragraph', content: "Security controls are the specific measures you implement to protect systems. Frameworks organize these controls into a structured approach. Without a framework, security is ad-hoc — you patch random things and hope for the best. With a framework, you systematically cover all bases." },
    { type: 'callout', variant: 'info', content: "Analogy: A security framework is like a building code for houses. It tells you: install smoke detectors (detective control), use fire-resistant materials (preventive control), and have fire extinguishers (corrective control). Without the building code, builders might forget critical safety measures." },
    { type: 'heading', level: 2, content: 'Types of Security Controls' },
    { type: 'list', items: ["Preventive — Stop attacks before they happen (firewalls, encryption, access control)", "Detective — Identify attacks in progress (IDS, SIEM, log monitoring, alerts)", "Corrective — Fix damage after an attack (backups, incident response, patching)", "Deterrent — Discourage attacks (security cameras, warning banners, legal notices)", "Compensating — Alternative controls when primary ones cannot be implemented"] },
    { type: 'heading', level: 2, content: 'Major Security Frameworks' },
    { type: 'heading', level: 3, content: 'NIST Cybersecurity Framework (CSF)' },
    { type: 'paragraph', content: "The most widely used framework in the US. Organized into 5 core functions:" },
    { type: 'list', items: ["Identify — Know your assets, risks, and business context", "Protect — Implement safeguards (access control, training, encryption)", "Detect — Discover security events quickly (monitoring, anomaly detection)", "Respond — Take action when incidents occur (containment, communication)", "Recover — Restore normal operations (backups, disaster recovery)"] },
    { type: 'heading', level: 3, content: 'ISO 27001' },
    { type: 'list', items: ["International standard for Information Security Management Systems (ISMS)", "Requires formal risk assessment and treatment plan", "114 controls across 14 domains (access control, cryptography, physical security, etc.)", "Certifiable — organizations can be audited and certified as compliant", "Widely required in Europe and for international business"] },
    { type: 'heading', level: 3, content: 'CIS Controls (v8)' },
    { type: 'list', items: ["18 prioritized, actionable security controls", "Designed as a practical starting point (not comprehensive like ISO 27001)", "Top 6 (Implementation Group 1) cover 85% of common attacks", "Control 1: Inventory of Enterprise Assets", "Control 2: Inventory of Software Assets", "Control 3: Data Protection", "Control 4: Secure Configuration", "Control 5: Account Management", "Control 6: Access Control Management"] },
    { type: 'heading', level: 2, content: 'Defense in Depth' },
    { type: 'paragraph', content: "No single control is perfect. Defense in Depth layers multiple controls so if one fails, others still protect you:" },
    { type: 'list', items: ["Layer 1: Perimeter — Firewall, WAF, DDoS protection", "Layer 2: Network — Segmentation, IDS/IPS, VPN", "Layer 3: Host — Antivirus, host firewall, patching", "Layer 4: Application — Input validation, authentication, encryption", "Layer 5: Data — Encryption at rest, access control, backups", "Layer 6: People — Security awareness training, policies, procedures"] },
    { type: 'callout', variant: 'security', content: "Real-world application: When you see a job posting requiring 'experience with NIST CSF' or 'ISO 27001 implementation,' they want someone who can build a structured security program — not just random technical fixes. Frameworks make you strategic, not just tactical." },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: ["Controls are specific measures (firewall, encryption, training)", "Frameworks organize controls into a structured program (NIST, ISO, CIS)", "Defense in Depth layers multiple controls — never rely on just one", "NIST CSF: Identify, Protect, Detect, Respond, Recover", "CIS Top 6 controls stop 85% of common attacks", "Next: Career paths and certifications in cybersecurity"] },
  ],
  navigation: {
    prev: { title: 'Types of Attackers & Motivations', slug: 'types-of-attackers' },
    next: { title: 'Cybersecurity Careers & Certifications', slug: 'cybersecurity-careers' },
  },
};
