export const lesson = {
  id: 'L06',
  title: 'Cybersecurity Careers & Certifications',
  slug: 'cybersecurity-careers',
  type: 'THEORY',
  duration: 20,
  xpReward: 10,
  difficulty: 'beginner',
  module: { title: 'Introduction to Cybersecurity', slug: 'intro-cybersecurity' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['SOC Analyst', 'Pentester', 'CISO', 'CompTIA Security+', 'CEH', 'OSCP', 'CISSP'],
  content: [
    { type: 'heading', content: 'Cybersecurity Careers & Certifications' },
    { type: 'paragraph', content: "Cybersecurity offers diverse career paths with strong demand and high salaries. There are 3.5 million unfilled cybersecurity jobs globally. This lesson maps out the major roles and the certifications that help you get hired." },
    { type: 'heading', level: 2, content: 'Career Paths' },
    { type: 'heading', level: 3, content: 'SOC Analyst (Entry Level)' },
    { type: 'list', items: ["Monitor security alerts and investigate suspicious activity", "Salary: $55K-$85K (Tier 1), $75K-$110K (Tier 2)", "Skills: Log analysis, SIEM tools, incident triage, basic networking", "Certs: CompTIA Security+, CySA+, Splunk Core Certified"] },
    { type: 'heading', level: 3, content: 'Penetration Tester (Mid Level)' },
    { type: 'list', items: ["Authorized hacking to find vulnerabilities before attackers do", "Salary: $85K-$140K", "Skills: Nmap, Metasploit, Burp Suite, scripting (Python/Bash)", "Certs: OSCP (gold standard), CEH, GPEN"] },
    { type: 'heading', level: 3, content: 'Security Engineer (Mid Level)' },
    { type: 'list', items: ["Build and maintain security infrastructure (firewalls, SIEM, IAM)", "Salary: $90K-$150K", "Skills: Cloud security, automation, networking, system administration", "Certs: AWS Security Specialty, CCSP, CompTIA CASP+"] },
    { type: 'heading', level: 3, content: 'Incident Responder / Forensics (Mid-Senior)' },
    { type: 'list', items: ["Investigate breaches, contain damage, recover systems, preserve evidence", "Salary: $90K-$145K", "Skills: Disk/memory forensics, malware analysis, timeline reconstruction", "Certs: GCIH, GCFA, EnCE"] },
    { type: 'heading', level: 3, content: 'Security Architect / CISO (Senior)' },
    { type: 'list', items: ["Design security strategy, manage teams, communicate risk to executives", "Salary: $150K-$300K+", "Skills: Leadership, risk management, compliance, business acumen", "Certs: CISSP, CISM, CCISO"] },
    { type: 'heading', level: 2, content: 'Key Certifications' },
    { type: 'list', items: ["CompTIA Security+ — Best entry-level cert. Covers fundamentals broadly.", "CEH (Certified Ethical Hacker) — Offensive security concepts (theory-heavy)", "OSCP — Practical pentesting exam (24-hour hands-on test). Gold standard for pentesters.", "CISSP — Senior-level management cert. Required for CISO/architect roles.", "AWS Security Specialty — Cloud security. Increasingly required.", "CySA+ — Blue team/SOC focused. Good for analysts."] },
    { type: 'callout', variant: 'security', content: "Career advice: Start with Security+ or a SOC analyst role. Build hands-on skills with labs (like this platform). After 2-3 years, specialize in offensive (OSCP) or defensive (GCIH) based on what you enjoy. Certifications open doors, but skills get you through the interview." },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: ["3.5 million unfilled jobs — demand is massive and growing", "Entry: SOC Analyst ($55-85K) with Security+ certification", "Mid: Pentester ($85-140K) or Security Engineer ($90-150K)", "Senior: Architect/CISO ($150-300K+) with CISSP", "Hands-on skills matter more than certifications alone", "Next: Setting up your own security lab to practice everything"] },
  ],
  navigation: {
    prev: { title: 'Security Controls & Frameworks', slug: 'security-controls-frameworks' },
    next: { title: 'Setting Up Your Security Lab', slug: 'setting-up-security-lab' },
  },
};
