export const lesson = {
  id: 'L07',
  title: 'Setting Up Your Security Lab',
  slug: 'setting-up-security-lab',
  type: 'PRACTICAL',
  duration: 40,
  xpReward: 25,
  difficulty: 'beginner',
  module: { title: 'Introduction to Cybersecurity', slug: 'intro-cybersecurity' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['Virtual Machine', 'VirtualBox', 'Kali Linux', 'Isolated Network', 'Snapshot', 'NAT', 'Host-Only'],
  content: [
    { type: 'heading', content: 'Setting Up Your Security Lab' },
    { type: 'paragraph', content: "A security lab is an isolated environment where you can practice attacks and defenses without risking real systems. Using virtual machines, you create entire networks on your laptop — targets to hack, tools to use, and nothing connected to the real internet." },
    { type: 'callout', variant: 'info', content: "Analogy: A security lab is like a flight simulator for pilots. You can crash the plane (break systems), practice emergency procedures (incident response), and try dangerous maneuvers (exploits) — all without any real-world consequences. Every security professional needs one." },
    { type: 'heading', level: 2, content: 'What You Need' },
    { type: 'list', items: ["A computer with at least 8GB RAM (16GB recommended)", "50GB free disk space (VMs use disk space)", "VirtualBox (free) or VMware Workstation Player (free for personal use)", "Kali Linux ISO (free download from kali.org)", "A vulnerable target VM (Metasploitable, DVWA, HackTheBox)"] },
    { type: 'heading', level: 2, content: 'Step 1: Install VirtualBox' },
    { type: 'command', command: 'sudo apt install virtualbox virtualbox-ext-pack', output: "Reading package lists... Done\nSetting up virtualbox (7.0.14) ...\nSetting up virtualbox-ext-pack (7.0.14) ...", explanation: "On Linux: install from package manager. On Windows/Mac: download the installer from virtualbox.org. VirtualBox lets you run multiple operating systems simultaneously." },
    { type: 'heading', level: 2, content: 'Step 2: Download Kali Linux' },
    { type: 'paragraph', content: "Download the pre-built VM image from kali.org/get-kali (Virtual Machines tab). This avoids the installation process — just import and run." },
    { type: 'command', command: 'sha256sum kali-linux-2024.1-virtualbox-amd64.ova', output: "a1b2c3d4e5f6... (compare with hash on kali.org)", explanation: "ALWAYS verify the hash after downloading. If it does not match, the file may be corrupted or tampered with (supply chain attack)." },
    { type: 'heading', level: 2, content: 'Step 3: Network Configuration' },
    { type: 'paragraph', content: "This is the most important step for safety. Configure your VM network correctly:" },
    { type: 'list', items: ["NAT — VM can access internet through your host (for updates only)", "Host-Only — VM can only talk to your host and other VMs (ISOLATED — use for attacks)", "Internal Network — VMs talk to each other only (best for attack labs)", "NEVER use Bridged mode for attack VMs — they would be on your real network!"] },
    { type: 'callout', variant: 'security', content: "CRITICAL: Always use Host-Only or Internal Network for attack practice. If you accidentally run an exploit on Bridged mode, it could hit real devices on your network. Isolate, isolate, isolate." },
    { type: 'heading', level: 2, content: 'Step 4: Take Snapshots' },
    { type: 'paragraph', content: "Before starting any lab exercise, take a VM snapshot. If something breaks, you can instantly revert to the clean state:" },
    { type: 'command', command: 'VBoxManage snapshot "Kali" take "Clean-State" --description "Before lab exercise"', output: "0%...10%...20%...100%\nSnapshot taken.", explanation: "Snapshots save the exact state of a VM. After completing a lab (or breaking something), revert to this snapshot for a fresh start. Like an undo button for entire operating systems." },
    { type: 'heading', level: 2, content: 'Recommended Lab Setup' },
    { type: 'list', items: ["VM 1: Kali Linux (your attacker/analyst machine — all tools pre-installed)", "VM 2: Metasploitable 2 (intentionally vulnerable Linux target)", "VM 3: DVWA on Ubuntu (vulnerable web application for web security practice)", "VM 4: Windows 10 (for Windows-specific attacks and Active Directory labs)", "Network: All VMs on the same Host-Only network (isolated from real network)"] },
    { type: 'heading', level: 2, content: 'First Commands in Kali' },
    { type: 'command', command: 'whoami && uname -a', output: "kali\nLinux kali 6.1.0-kali9-amd64 #1 SMP x86_64 GNU/Linux", explanation: "Verify you are logged in as the kali user on a Kali Linux system. Your attack machine is ready." },
    { type: 'command', command: 'ip addr show eth0 | grep inet', output: "    inet 192.168.56.10/24 brd 192.168.56.255 scope global eth0", explanation: "Your Kali machine has IP 192.168.56.10 on the Host-Only network. Target VMs will be on the same 192.168.56.0/24 subnet." },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: ["Use VirtualBox to create isolated virtual machines", "Kali Linux is your primary security toolkit (600+ tools pre-installed)", "ALWAYS use Host-Only or Internal Network — never Bridged for attack labs", "Take snapshots before every exercise — instant rollback if something breaks", "Your lab is your safe space to practice everything in this course", "Next module: Linux Fundamentals — mastering the command line"] },
  ],
  navigation: {
    prev: { title: 'Cybersecurity Careers & Certifications', slug: 'cybersecurity-careers' },
    next: { title: 'Introduction to Linux', slug: 'intro-linux' },
  },
};
