export const lesson = {
  id: 'L10',
  title: 'File Operations & Text Processing',
  slug: 'linux-file-operations',
  type: 'PRACTICAL',
  duration: 40,
  xpReward: 25,
  difficulty: 'beginner',
  module: { title: 'Linux Fundamentals', slug: 'linux-fundamentals' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['cat', 'grep', 'awk', 'sed', 'head', 'tail', 'wc', 'sort', 'pipe', 'redirect'],
  content: [
    { type: 'heading', content: 'File Operations & Text Processing' },
    { type: 'paragraph', content: "Reading and processing text files is the bread and butter of security work. Log analysis, configuration auditing, and forensics all require you to quickly extract relevant information from large files. These commands are your essential toolkit." },
    { type: 'callout', variant: 'info', content: "Analogy: If the filesystem is a library, cat reads the book, grep finds a specific word across all pages, awk extracts specific columns from a table, and sed does find-and-replace. Pipes (|) chain them together like an assembly line." },
    { type: 'heading', level: 2, content: 'cat — Display File Contents' },
    { type: 'command', command: 'cat /etc/hostname', output: 'security-lab', explanation: "cat outputs the entire file to your screen. For small files like configs, it is the fastest way to read them." },
    { type: 'command', command: 'cat -n /etc/passwd | head -5', output: "     1\troot:x:0:0:root:/root:/bin/bash\n     2\tdaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\n     3\tbin:x:2:2:bin:/bin:/usr/sbin/nologin\n     4\tsys:x:3:3:sys:/dev:/usr/sbin/nologin\n     5\tsync:x:4:65534:sync:/bin:/bin/sync", explanation: "-n adds line numbers. Piping to head -5 shows only the first 5 lines. /etc/passwd contains all user accounts — critical for security auditing." },
    { type: 'heading', level: 2, content: 'grep — Search for Patterns' },
    { type: 'paragraph', content: "grep is the most important text-processing command for security. It searches files for lines matching a pattern:" },
    { type: 'command', command: 'grep "Failed" /var/log/auth.log | tail -5', output: "Jun 15 03:14:22 server sshd[4521]: Failed password for root from 203.0.113.50 port 45678\nJun 15 03:14:25 server sshd[4523]: Failed password for root from 203.0.113.50 port 45679\nJun 15 03:14:28 server sshd[4525]: Failed password for admin from 203.0.113.50 port 45680\nJun 15 03:14:31 server sshd[4527]: Failed password for root from 203.0.113.50 port 45681\nJun 15 03:14:34 server sshd[4529]: Failed password for root from 203.0.113.50 port 45682", explanation: "Searches auth.log for failed login attempts. This reveals a brute-force attack from 203.0.113.50 trying root and admin passwords repeatedly." },
    { type: 'command', command: 'grep -c "Failed" /var/log/auth.log', output: "2847", explanation: "-c counts matching lines instead of showing them. 2847 failed login attempts — definitely a brute-force attack." },
    { type: 'command', command: 'grep -r "password" /etc/ 2>/dev/null | head -3', output: "/etc/pam.d/common-password:password requisite pam_pwquality.so\n/etc/login.defs:PASS_MAX_DAYS 90\n/etc/login.defs:PASS_MIN_LEN 8", explanation: "-r searches recursively through all files in /etc/. Finds password-related configurations — useful for auditing password policies." },
    { type: 'heading', level: 2, content: 'head & tail — View File Portions' },
    { type: 'command', command: 'head -20 /var/log/syslog', output: "Jun 15 00:00:01 server systemd[1]: Starting Daily apt...", explanation: "head shows the first N lines. Useful for checking file headers or the beginning of logs." },
    { type: 'command', command: 'tail -f /var/log/auth.log', output: "Jun 15 10:45:01 server sshd[5678]: Accepted publickey for analyst from 10.0.1.50\n(waiting for new entries...)", explanation: "tail -f follows the file in real-time — new lines appear as they are written. Essential for live monitoring during incident response. Press Ctrl+C to stop." },
    { type: 'heading', level: 2, content: 'Pipes & Chaining Commands' },
    { type: 'paragraph', content: "The pipe operator (|) sends one command's output as input to the next. This is what makes Linux so powerful for data processing:" },
    { type: 'command', command: 'grep "Failed" /var/log/auth.log | awk \'{print $11}\' | sort | uniq -c | sort -rn | head -5', output: "   2341 203.0.113.50\n    312 198.51.100.25\n     98 192.0.2.100\n     54 10.0.5.200\n     42 172.16.0.50", explanation: "This pipeline: (1) finds failed logins, (2) extracts the IP field, (3) sorts them, (4) counts unique IPs, (5) sorts by count descending, (6) shows top 5. Result: 203.0.113.50 is the primary attacker with 2341 attempts!" },
    { type: 'callout', variant: 'security', content: "This exact pipeline is used daily by SOC analysts to identify brute-force attackers from authentication logs. Master pipes and you can process millions of log lines in seconds." },
    { type: 'heading', level: 2, content: 'wc — Count Lines, Words, Characters' },
    { type: 'command', command: 'wc -l /var/log/auth.log', output: "45231 /var/log/auth.log", explanation: "-l counts lines. 45,231 log entries to analyze. Combined with grep: grep 'Failed' auth.log | wc -l gives the count of failed attempts." },
    { type: 'heading', level: 2, content: 'awk — Column Extraction' },
    { type: 'command', command: "awk -F: '{print $1, $7}' /etc/passwd | head -5", output: "root /bin/bash\ndaemon /usr/sbin/nologin\nbin /usr/sbin/nologin\nsys /usr/sbin/nologin\nsync /bin/sync", explanation: "-F: sets the delimiter to colon. Prints column 1 (username) and column 7 (shell). Users with /bin/bash can log in interactively — important for security auditing." },
    { type: 'heading', level: 2, content: 'Output Redirection' },
    { type: 'list', items: [
      "> — Redirect output to a file (overwrites): grep 'Failed' auth.log > failed_logins.txt",
      ">> — Append to file: echo 'new entry' >> log.txt",
      "2> — Redirect errors: find / -name secret 2>/dev/null (hides permission errors)",
      "| — Pipe output to another command: cat file | grep pattern | wc -l"
    ]},
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: [
      "cat reads files, head/tail show beginnings/ends, tail -f monitors in real-time",
      "grep searches for patterns — your #1 tool for log analysis",
      "awk extracts specific columns from structured data",
      "Pipes (|) chain commands into powerful data processing pipelines",
      "sort | uniq -c | sort -rn is the magic recipe for counting occurrences",
      "Next: Users, groups, and permissions — controlling who can do what"
    ]},
  ],
  navigation: {
    prev: { title: 'Navigating the File System', slug: 'linux-filesystem' },
    next: { title: 'Users, Groups & Permissions', slug: 'linux-users-permissions' },
  },
};
