export const lesson = {
  id: 'L11',
  title: 'Users, Groups & Permissions',
  slug: 'linux-users-permissions',
  type: 'PRACTICAL',
  duration: 45,
  xpReward: 25,
  difficulty: 'beginner',
  module: { title: 'Linux Fundamentals', slug: 'linux-fundamentals' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['User', 'Group', 'UID', 'GID', 'useradd', 'passwd', 'chmod', 'chown', 'sudo'],
  content: [
    { type: 'heading', content: 'Users, Groups & Permissions' },
    { type: 'paragraph', content: "Linux is a multi-user system — multiple people (or services) can use the same machine simultaneously. The permission system controls who can read, write, and execute each file. Understanding this is fundamental to both attacking and defending Linux systems." },
    { type: 'callout', variant: 'info', content: "Analogy: Users are like employees with ID badges. Groups are like departments (Marketing, Engineering). Permissions are like door locks — some doors open for everyone, some only for specific departments, and some only for specific individuals." },
    { type: 'heading', level: 2, content: 'Understanding Users' },
    { type: 'command', command: 'cat /etc/passwd | grep -v nologin | grep -v false', output: "root:x:0:0:root:/root:/bin/bash\nanalyst:x:1000:1000:Security Analyst:/home/analyst:/bin/bash\njohn:x:1001:1001:John Smith:/home/john:/bin/bash\nsuspicious_user:x:1002:1002::/home/suspicious_user:/bin/bash", explanation: "Shows users who can actually log in (have a real shell). Each line: username:password(x=in shadow):UID:GID:comment:home:shell. UID 0 = root (superuser). UID 1000+ = regular users." },
    { type: 'command', command: 'id analyst', output: "uid=1000(analyst) gid=1000(analyst) groups=1000(analyst),27(sudo),4(adm)", explanation: "Shows user details: UID 1000, primary group 1000, also member of sudo (can run admin commands) and adm (can read logs)." },
    { type: 'heading', level: 2, content: 'File Permissions Explained' },
    { type: 'command', command: 'ls -la /etc/shadow', output: "-rw-r----- 1 root shadow 1245 Jun 15 10:00 /etc/shadow", explanation: "Permissions: -rw-r----- means: owner (root) can read/write, group (shadow) can read, others have NO access. The shadow file contains password hashes — only root can modify it." },
    { type: 'paragraph', content: "Permission breakdown: rwx rwx rwx (Owner, Group, Others)" },
    { type: 'list', items: [
      "r (read=4) — Can view file contents or list directory",
      "w (write=2) — Can modify file or create/delete files in directory",
      "x (execute=1) — Can run file as program or enter directory",
      "- means that permission is NOT granted",
      "Example: rwxr-xr-- = Owner: full, Group: read+execute, Others: read only"
    ]},
    { type: 'heading', level: 2, content: 'chmod — Change Permissions' },
    { type: 'command', command: 'chmod 700 ~/.ssh/id_rsa', output: '', explanation: "Sets SSH private key to rwx------ (only owner can access). SSH REQUIRES this — it refuses to use keys with loose permissions. 7=rwx, 0=---, 0=---." },
    { type: 'command', command: 'chmod u+x script.sh', output: '', explanation: "Adds execute permission for the owner (u=user). Now you can run ./script.sh. Symbolic mode: u/g/o for user/group/others, +/- to add/remove, r/w/x for permissions." },
    { type: 'heading', level: 2, content: 'chown — Change Ownership' },
    { type: 'command', command: 'sudo chown root:root /etc/important.conf', output: '', explanation: "Changes owner AND group to root. Only root can now modify this file (assuming 600 permissions). Critical for securing config files." },
    { type: 'heading', level: 2, content: 'sudo — Temporary Root Access' },
    { type: 'command', command: 'sudo cat /etc/shadow | head -3', output: "root:$6$xyz...:19500:0:99999:7:::\nanalyst:$6$abc...:19520:0:99999:7:::\njohn:$6$def...:19530:0:99999:7:::", explanation: "sudo runs a command as root. /etc/shadow is readable only by root — sudo lets authorized users access it temporarily. The $6$ prefix means SHA-512 hashing." },
    { type: 'callout', variant: 'security', content: "Security principle: Users should have the MINIMUM permissions needed for their job (least privilege). Never give sudo access to everyone. Never run services as root. Overly permissive permissions are the #1 cause of privilege escalation." },
    { type: 'heading', level: 2, content: 'Creating Users & Groups' },
    { type: 'command', command: 'sudo useradd -m -s /bin/bash -G sudo newuser', output: '', explanation: "-m creates home directory, -s sets shell, -G adds to supplementary group (sudo). This creates a user who can run admin commands." },
    { type: 'command', command: 'sudo passwd newuser', output: "New password:\nRetype new password:\npasswd: password updated successfully", explanation: "Sets the password for the new user. Without this step, the account exists but cannot log in with a password." },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: [
      "Every file has an owner, a group, and permissions (rwx) for owner/group/others",
      "chmod changes permissions, chown changes ownership",
      "Numeric mode: 7=rwx, 6=rw-, 5=r-x, 4=r--, 0=---",
      "sudo grants temporary root access — audit who has it with: grep sudo /etc/group",
      "/etc/passwd lists users, /etc/shadow stores password hashes (root-only)",
      "Next: Advanced permissions — SUID, SGID, sticky bit, and security implications"
    ]},
  ],
  navigation: {
    prev: { title: 'File Operations & Text Processing', slug: 'linux-file-operations' },
    next: { title: 'Linux File Permissions Deep Dive', slug: 'linux-file-permissions' },
  },
};
