export const lesson = {
  id: 'L12',
  title: 'Linux File Permissions Deep Dive',
  slug: 'linux-file-permissions',
  type: 'PRACTICAL',
  duration: 40,
  xpReward: 25,
  difficulty: 'beginner',
  module: { title: 'Linux Fundamentals', slug: 'linux-fundamentals' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['SUID', 'SGID', 'Sticky Bit', 'umask', 'Privilege Escalation', 'World-Writable'],
  content: [
    { type: 'heading', content: 'Linux File Permissions Deep Dive' },
    { type: 'paragraph', content: "Beyond basic rwx permissions, Linux has special permission bits that are critical for security. SUID, SGID, and sticky bits can either protect systems or become attack vectors. Understanding them is essential for both hardening and privilege escalation." },
    { type: 'callout', variant: 'info', content: "Analogy: SUID is like a valet key — when you use it, you temporarily get the car owner's privileges (root access) just for that one task. If an attacker finds a broken valet key (vulnerable SUID binary), they get full access to the car." },
    { type: 'heading', level: 2, content: 'SUID (Set User ID)' },
    { type: 'paragraph', content: "When SUID is set on an executable, it runs with the permissions of the FILE OWNER, not the user who launched it. This is how normal users can change their password (passwd is SUID root)." },
    { type: 'command', command: 'ls -la /usr/bin/passwd', output: "-rwsr-xr-x 1 root root 68208 Jun 15 /usr/bin/passwd", explanation: "The 's' in the owner execute position means SUID is set. When ANY user runs passwd, it executes as root — necessary because only root can write to /etc/shadow." },
    { type: 'command', command: 'find / -perm -4000 -type f 2>/dev/null', output: "/usr/bin/passwd\n/usr/bin/sudo\n/usr/bin/chfn\n/usr/bin/newgrp\n/usr/bin/mount\n/usr/bin/su\n/usr/bin/pkexec\n/opt/custom/backup_tool", explanation: "Finds ALL SUID files on the system. Standard ones (passwd, sudo, mount) are expected. But /opt/custom/backup_tool is unusual — potential privilege escalation vector!" },
    { type: 'callout', variant: 'security', content: "SUID privilege escalation: If a SUID-root binary has a vulnerability (buffer overflow, path injection, improper input handling), an attacker can exploit it to get root access. ALWAYS audit SUID files: find / -perm -4000 2>/dev/null and investigate anything unexpected." },
    { type: 'heading', level: 2, content: 'SGID (Set Group ID)' },
    { type: 'paragraph', content: "Similar to SUID but for groups. On a directory, SGID makes all new files inherit the directory group (useful for shared team folders)." },
    { type: 'command', command: 'find / -perm -2000 -type f 2>/dev/null | head -5', output: "/usr/bin/wall\n/usr/bin/write\n/usr/bin/crontab\n/usr/bin/ssh-agent\n/usr/sbin/postdrop", explanation: "SGID files run with the group permission of the file. Less commonly exploited than SUID but still worth auditing." },
    { type: 'heading', level: 2, content: 'Sticky Bit' },
    { type: 'paragraph', content: "The sticky bit on a directory means only the file owner (or root) can delete files in that directory — even if others have write permission. Applied to /tmp to prevent users from deleting each other's temporary files." },
    { type: 'command', command: 'ls -ld /tmp', output: "drwxrwxrwt 12 root root 4096 Jun 15 10:00 /tmp", explanation: "The 't' at the end means sticky bit is set. Everyone can write to /tmp (rwxrwxrwx) but only file owners can delete their own files. Without this, any user could delete anyone's temp files." },
    { type: 'heading', level: 2, content: 'World-Writable Files (Security Risk)' },
    { type: 'command', command: 'find / -perm -002 -type f 2>/dev/null | grep -v proc', output: "/tmp/notes.txt\n/var/www/html/config.php\n/opt/app/settings.ini", explanation: "Finds files writable by ANYONE. /tmp is expected, but config.php and settings.ini being world-writable is a serious misconfiguration — any user can modify application settings!" },
    { type: 'heading', level: 2, content: 'umask — Default Permission Mask' },
    { type: 'command', command: 'umask', output: "0022", explanation: "umask subtracts from default permissions. Files default to 666, directories to 777. With umask 022: files get 644 (rw-r--r--), directories get 755 (rwxr-xr-x). A stricter umask (077) gives 600/700." },
    { type: 'heading', level: 2, content: 'Security Auditing Checklist' },
    { type: 'list', items: [
      "find / -perm -4000 — List all SUID files (investigate unknowns)",
      "find / -perm -002 -type f — Find world-writable files (fix permissions)",
      "find / -nouser -o -nogroup — Files with no valid owner (orphaned)",
      "find /home -name '.*' -type f — Hidden files in home dirs (potential backdoors)",
      "stat filename — Show detailed file metadata including access/modify times"
    ]},
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: [
      "SUID (4000): File runs as the file owner — #1 privilege escalation vector",
      "SGID (2000): File runs with file group / directory inherits group",
      "Sticky bit (1000): Only owner can delete in shared directories (/tmp)",
      "World-writable files are security risks — audit regularly",
      "umask controls default permissions for new files",
      "Next: Services, daemons, and systemd — managing what runs on the system"
    ]},
  ],
  navigation: {
    prev: { title: 'Users, Groups & Permissions', slug: 'linux-users-permissions' },
    next: { title: 'Services, Daemons & Systemd', slug: 'linux-services-systemd' },
  },
};
