export const lesson = {
  id: 'L13',
  title: 'Services, Daemons & Systemd',
  slug: 'linux-services-systemd',
  type: 'PRACTICAL',
  duration: 35,
  xpReward: 20,
  difficulty: 'beginner',
  module: { title: 'Linux Fundamentals', slug: 'linux-fundamentals' },
  course: { title: 'CyberSec Academy', slug: 'cybersec-academy' },
  keyTerms: ['Service', 'Daemon', 'systemd', 'systemctl', 'journalctl', 'Unit File', 'Enable', 'Boot'],
  content: [
    { type: 'heading', content: 'Services, Daemons & Systemd' },
    { type: 'paragraph', content: "Services (daemons) are programs that run in the background continuously — web servers, SSH, databases, firewalls. Systemd manages them all. Knowing which services are running and controlling them is essential for both hardening systems and investigating compromises." },

    { type: 'callout', variant: 'info', content: "Analogy: Daemons are like building utilities — heating, electricity, water. They start when the building opens (boot), run silently in the background, and you only notice them when they fail. systemd is the building manager who starts, stops, and monitors all of them." },
    { type: 'heading', level: 2, content: 'Listing Running Services' },
    { type: 'command', command: 'systemctl list-units --type=service --state=running | head -10', output: "UNIT                     LOAD   ACTIVE SUB     DESCRIPTION\naccounts-daemon.service  loaded active running Accounts Service\napache2.service          loaded active running Apache HTTP Server\ncron.service             loaded active running Regular background processing\ndocker.service           loaded active running Docker Engine\nmysql.service            loaded active running MySQL Server\nssh.service              loaded active running OpenBSD Secure Shell server\nrsyslog.service          loaded active running System Logging Service", explanation: "Lists all currently running services. Know your baseline — any unexpected service (crypto miner, backdoor listener) should be investigated immediately." },
    { type: 'heading', level: 2, content: 'Controlling Services' },
    { type: 'command', command: 'sudo systemctl status ssh', output: "ssh.service - OpenBSD Secure Shell server\n   Loaded: loaded (/lib/systemd/system/ssh.service; enabled)\n   Active: active (running) since Mon 2024-06-15 09:00:00 UTC; 5h ago\n Main PID: 847 (sshd)\n    Tasks: 1\n   Memory: 4.2M\n   CGroup: /system.slice/ssh.service\n           847 sshd: /usr/sbin/sshd -D", explanation: "Shows service status: loaded, enabled (starts at boot), active for 5 hours, PID 847, using 4.2MB RAM. The CGroup line shows the actual process." },
    { type: 'command', command: 'sudo systemctl stop apache2', output: '', explanation: "Stops the Apache web server immediately. Use this during incident response to take a compromised service offline." },
    { type: 'command', command: 'sudo systemctl disable apache2', output: "Removed /etc/systemd/system/multi-user.target.wants/apache2.service.", explanation: "Prevents Apache from starting at boot. stop = stop now. disable = don't start at boot. Do both to fully decommission a service." },
    { type: 'command', command: 'sudo systemctl enable --now ufw', output: "Created symlink /etc/systemd/system/multi-user.target.wants/ufw.service", explanation: "--now combines enable (start at boot) and start (start now) in one command. Used when activating a new security service like the firewall." },
    { type: 'heading', level: 2, content: 'Reading Logs with journalctl' },
    { type: 'command', command: 'journalctl -u ssh --since "1 hour ago" | tail -5', output: "Jun 15 14:30:01 server sshd[5678]: Accepted publickey for analyst from 10.0.1.50 port 52341\nJun 15 14:32:15 server sshd[5690]: Failed password for root from 203.0.113.50 port 45678\nJun 15 14:32:18 server sshd[5692]: Failed password for root from 203.0.113.50 port 45679\nJun 15 14:32:21 server sshd[5694]: Failed password for root from 203.0.113.50 port 45680\nJun 15 14:35:00 server sshd[5700]: Accepted password for john from 192.168.1.20 port 49876", explanation: "journalctl shows logs for a specific service (-u ssh) within a time range. Here we see: a legitimate login (analyst via key), a brute-force attempt (203.0.113.50), and another legitimate login (john)." },
    { type: 'command', command: 'journalctl -p err -b', output: "Jun 15 09:00:15 server kernel: EXT4-fs error (device sda1): ...\nJun 15 10:30:42 server apache2[1234]: AH00526: Syntax error on line 42", explanation: "-p err shows only error-level messages. -b means current boot only. Quick way to find problems — filesystem errors and service configuration mistakes." },
    { type: 'callout', variant: 'security', content: "Security hardening: Disable and stop ALL services you do not need. Every running service is an attack surface. A minimal server should run only: SSH, firewall, your application, and logging. Remove everything else." },
    { type: 'heading', level: 2, content: 'Finding Suspicious Services' },
    { type: 'command', command: 'systemctl list-unit-files --type=service | grep enabled | grep -v "systemd\\|ssh\\|cron\\|rsyslog\\|network"', output: "apache2.service          enabled\ndocker.service           enabled\nmysql.service            enabled\nbackdoor-update.service  enabled", explanation: "Lists all enabled services, filtering out known system services. 'backdoor-update.service' looks suspicious — it is not a standard service. Investigate with: systemctl cat backdoor-update.service" },
    { type: 'heading', level: 2, content: 'Summary' },
    { type: 'list', items: [
      "systemctl status/start/stop/enable/disable controls services",
      "journalctl -u SERVICE reads service-specific logs with time filtering",
      "Every running service is attack surface — disable what you do not need",
      "Know your baseline services — investigate anything unfamiliar",
      "Attackers create malicious services for persistence — audit regularly",
      "Next: Process management — viewing and controlling running programs"
    ]},
  ],
  navigation: {
    prev: { title: 'Linux File Permissions Deep Dive', slug: 'linux-file-permissions' },
    next: { title: 'Linux Process Management & Monitoring', slug: 'linux-process-management' },
  },
};
