export const lesson = {
  id: 'L27',
  title: 'Network Services & Protocols (DNS, DHCP, HTTP)',
  slug: 'network-services-protocols',
  type: 'THEORY',
  duration: 40,
  xpReward: 25,
  difficulty: 'intermediate',
  module: { title: 'Computer Networking', slug: 'computer-networking' },
  course: { title: 'Network Fundamentals', slug: 'network-fundamentals' },
  keyTerms: [
    'DNS', 'DHCP', 'HTTP', 'HTTPS', 'FTP', 'SMTP', 'SNMP',
    'Port', 'Well-Known Ports', 'Service Enumeration', 'Banner Grabbing'
  ],
  content: [
    { type: 'heading', content: 'Network Services & Protocols: DNS, DHCP, HTTP' },
    { type: 'paragraph', content: 'Network services are the programs that make the internet useful — they translate names to addresses (DNS), assign IP configurations (DHCP), and deliver web pages (HTTP). Understanding how they work reveals how attackers exploit them.' },

    { type: 'callout', variant: 'info', content: 'Analogy: Think of network services like utility companies. DNS is the phone company (looks up numbers from names). DHCP is the housing authority (assigns addresses to new residents). HTTP is the postal service (delivers packages/web pages). Each can be attacked if not secured.' },

    { type: 'heading', level: 2, content: 'DNS: The Internet\'s Phone Book' },
    { type: 'paragraph', content: 'The Domain Name System translates human-readable names (google.com) into IP addresses (142.250.80.46). Without DNS, you\'d need to memorize IP addresses for every website.' },

    { type: 'heading', level: 3, content: 'How DNS Resolution Works' },
    { type: 'paragraph', content: 'When you type "example.com" in your browser, here\'s what happens:' },
    { type: 'list', items: [
      '1. Browser checks its local cache — "Have I looked this up before?"',
      '2. OS checks /etc/hosts file — "Is there a manual override?"',
      '3. OS asks the configured DNS resolver (usually your router or ISP)',
      '4. Resolver asks Root DNS servers → ".com" TLD servers → example.com\'s authoritative server',
      '5. Answer flows back: example.com = 93.184.216.34',
      '6. Result is cached at every level for the TTL (Time To Live) duration'
    ]},

    { type: 'command', command: 'cat /etc/resolv.conf', output: `# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
search home.local`, explanation: 'This file tells your system which DNS servers to use. The first one (192.168.1.1, your router) is tried first. If it fails, 8.8.8.8 (Google) is the backup.' },

    { type: 'command', command: 'dig +trace example.com', output: `.                     518400  IN  NS  a.root-servers.net.
.                     518400  IN  NS  b.root-servers.net.
;; Received 239 bytes from 192.168.1.1#53

com.                  172800  IN  NS  a.gtld-servers.net.
com.                  172800  IN  NS  b.gtld-servers.net.
;; Received 832 bytes from 198.41.0.4#53(a.root-servers.net)

example.com.          172800  IN  NS  ns1.example.com.
example.com.          172800  IN  NS  ns2.example.com.
;; Received 498 bytes from 192.5.6.30#53(a.gtld-servers.net)

example.com.          3600    IN  A   93.184.216.34
;; Received 56 bytes from 199.43.135.53#53(ns1.example.com)`, explanation: 'The +trace flag shows the full DNS resolution path: Root → .com TLD → example.com authoritative server. This is how the hierarchical DNS system works.' },

    { type: 'heading', level: 3, content: 'DNS Record Types' },
    { type: 'paragraph', content: 'DNS stores different types of records, each serving a specific purpose:' },
    { type: 'list', items: [
      'A Record — Maps hostname to IPv4 address (example.com → 93.184.216.34)',
      'AAAA Record — Maps hostname to IPv6 address',
      'MX Record — Mail exchange servers (where to deliver email)',
      'CNAME Record — Alias pointing to another hostname (www.example.com → example.com)',
      'NS Record — Authoritative nameservers for the domain',
      'TXT Record — Arbitrary text (used for SPF, DKIM, domain verification)',
      'PTR Record — Reverse DNS (IP to hostname)',
      'SOA Record — Start of Authority (zone administration info)'
    ]},

    { type: 'callout', variant: 'security', content: 'DNS attacks: DNS Cache Poisoning (redirect users to fake sites), DNS Tunneling (exfiltrate data through DNS queries), DNS Amplification DDoS (small query → large response used to flood victims), Zone Transfer exploitation (steal all DNS records if misconfigured).' },

    { type: 'command', command: 'dig axfr @ns1.target.com target.com', output: `; <<>> DiG 9.16.1 <<>> axfr @ns1.target.com target.com
; Transfer failed.`, explanation: 'Attempting a zone transfer — this would dump ALL DNS records for the domain. A properly configured server refuses this. If it succeeds, it\'s a serious misconfiguration revealing the entire network map.' },

    { type: 'heading', level: 2, content: 'DHCP: Automatic Network Configuration' },
    { type: 'paragraph', content: 'Dynamic Host Configuration Protocol automatically assigns IP addresses, subnet masks, gateways, and DNS servers to devices when they join a network. Without DHCP, every device would need manual network configuration.' },

    { type: 'heading', level: 3, content: 'The DHCP Process (DORA)' },
    { type: 'list', items: [
      'Discover — Client broadcasts "I need an IP address!" to the entire network',
      'Offer — DHCP server responds with an available IP and configuration',
      'Request — Client accepts the offer: "I\'ll take that IP, please"',
      'Acknowledge — Server confirms: "It\'s yours for the next 24 hours (lease time)"'
    ]},

    { type: 'command', command: 'sudo dhclient -v eth0', output: `Internet Systems Consortium DHCP Client 4.4.1
Listening on LPF/eth0/08:00:27:a5:b3:c1
Sending on   LPF/eth0/08:00:27:a5:b3:c1
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3
DHCPOFFER of 192.168.1.105 from 192.168.1.1
DHCPREQUEST for 192.168.1.105 on eth0 to 255.255.255.255 port 67
DHCPACK of 192.168.1.105 from 192.168.1.1
bound to 192.168.1.105 -- renewal in 43200 seconds.`, explanation: 'Manually requesting a DHCP lease. You can see the DORA process: Discover → Offer (192.168.1.105) → Request → Acknowledge. Lease renews in 43200 seconds (12 hours).' },

    { type: 'callout', variant: 'security', content: 'DHCP attacks: Rogue DHCP Server — attacker sets up their own DHCP server that hands out their machine as the gateway, enabling man-in-the-middle attacks. DHCP Starvation — attacker requests all available IPs, causing denial-of-service for legitimate users. Mitigation: DHCP snooping on managed switches.' },

    { type: 'heading', level: 2, content: 'HTTP/HTTPS: Web Communication' },
    { type: 'paragraph', content: 'HyperText Transfer Protocol is how browsers communicate with web servers. HTTPS adds encryption (TLS) to protect the data in transit.' },

    { type: 'heading', level: 3, content: 'HTTP Request and Response' },
    { type: 'command', command: 'curl -v http://example.com 2>&1 | head -30', output: `*   Trying 93.184.216.34:80...
* Connected to example.com (93.184.216.34) port 80 (#0)
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.81.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Content-Length: 1256
< Connection: keep-alive
< Cache-Control: max-age=604800
< Date: Sat, 15 Jun 2024 10:45:32 GMT
< Server: ECS (dcb/7FA3)
<
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
...`, explanation: 'curl -v shows the full HTTP conversation. Lines with ">" are what YOUR machine sends (request). Lines with "<" are what the SERVER sends back (response). HTTP 200 = success.' },

    { type: 'paragraph', content: 'Important HTTP status codes:' },
    { type: 'list', items: [
      '200 OK — Request succeeded, here\'s your data',
      '301/302 — Redirect to another URL',
      '400 Bad Request — Your request was malformed',
      '401 Unauthorized — Authentication required',
      '403 Forbidden — Authenticated but not allowed',
      '404 Not Found — Resource doesn\'t exist',
      '500 Internal Server Error — Server crashed (potential vulnerability indicator)',
      '503 Service Unavailable — Server overloaded (possible DDoS)'
    ]},

    { type: 'heading', level: 3, content: 'HTTPS and TLS' },
    { type: 'command', command: 'openssl s_client -connect example.com:443 -brief', output: `CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Peer certificate: CN = www.example.org
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits`, explanation: 'Checks the TLS/SSL configuration of a web server. TLSv1.3 is the latest and most secure version. The cipher suite and certificate details confirm secure communication.' },

    { type: 'callout', variant: 'security', content: 'Never transmit credentials over plain HTTP. Attackers on the same network can capture them with packet sniffing. Always verify HTTPS is used, especially on login pages and payment forms. Look for expired or self-signed certificates as phishing indicators.' },

    { type: 'heading', level: 2, content: 'Other Critical Network Services' },
    { type: 'paragraph', content: 'Beyond the big three, several other services are security-relevant:' },

    { type: 'heading', level: 3, content: 'FTP (Port 21) — File Transfer' },
    { type: 'command', command: 'ftp 192.168.1.50', output: `Connected to 192.168.1.50.
220 (vsFTPd 3.0.5)
Name (192.168.1.50:analyst): anonymous
331 Please specify the password.
Password: (blank)
230 Login successful.
ftp>`, explanation: 'FTP with anonymous login — a common misconfiguration that allows anyone to download (and sometimes upload) files. This is frequently exploited by attackers to plant malware or steal data.' },

    { type: 'heading', level: 3, content: 'SMTP (Port 25) — Email' },
    { type: 'command', command: 'nc -v mail.target.com 25', output: `Connection to mail.target.com 25 port [tcp/smtp] succeeded!
220 mail.target.com ESMTP Postfix
EHLO test.com
250-mail.target.com
250-PIPELINING
250-SIZE 10240000
250-AUTH PLAIN LOGIN
250 STARTTLS`, explanation: 'Connecting to an SMTP server reveals software version (Postfix), supported features, and auth methods. Attackers use this for email spoofing if the server lacks proper SPF/DKIM/DMARC configuration.' },

    { type: 'heading', level: 3, content: 'SNMP (Port 161) — Network Management' },
    { type: 'paragraph', content: 'Simple Network Management Protocol lets you monitor and manage network devices. If the default "public" community string hasn\'t been changed, attackers can read device configurations remotely — a goldmine of network information.' },

    { type: 'heading', level: 2, content: 'Well-Known Ports Reference' },
    { type: 'paragraph', content: 'As a security professional, you must recognize these ports on sight:' },
    { type: 'list', items: [
      'Port 20/21 — FTP (data/control)',
      'Port 22 — SSH (Secure Shell)',
      'Port 23 — Telnet (insecure remote access)',
      'Port 25 — SMTP (email sending)',
      'Port 53 — DNS',
      'Port 67/68 — DHCP (server/client)',
      'Port 80 — HTTP',
      'Port 110 — POP3 (email retrieval)',
      'Port 143 — IMAP (email retrieval)',
      'Port 443 — HTTPS',
      'Port 445 — SMB (Windows file sharing)',
      'Port 3306 — MySQL',
      'Port 3389 — RDP (Remote Desktop)',
      'Port 5432 — PostgreSQL',
      'Port 8080 — HTTP Proxy/Alt HTTP'
    ]},

    { type: 'heading', level: 2, content: 'Summary & Security Implications' },
    { type: 'paragraph', content: 'Network services are the attack surface of any organization. Every open port is a potential entry point:' },
    { type: 'list', items: [
      'DNS — Protect against cache poisoning, tunneling, and zone transfer leaks',
      'DHCP — Deploy DHCP snooping to prevent rogue servers',
      'HTTP — Always use HTTPS; inspect headers for information leakage',
      'FTP — Replace with SFTP; never allow anonymous access in production',
      'SMTP — Implement SPF, DKIM, and DMARC to prevent spoofing',
      'Minimize your attack surface: disable services you don\'t need',
      'Audit open ports regularly with ss and nmap',
      'Use banner grabbing to verify expected software versions'
    ]},
  ],
  navigation: {
    prev: { title: 'Network Troubleshooting & Diagnostics', slug: 'network-troubleshooting' },
    next: { title: 'Wireless Networking Fundamentals & Security', slug: 'wireless-networking' },
  },
};
